# cloudbuild.yaml

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--no-cache', '-t', 'gcr.io/bolgzenai/blogzenai-api:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/bolgzenai/blogzenai-api:latest']

images:
  - 'gcr.io/bolgzenai/blogzenai-api:latest'